services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube?useSSL=false
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/sonarqube_extensions
      - ./sonarqube_logs:/opt/sonarqube/sonarqube_logs
      - ./sonarqube_temp:/opt/sonarqube/temp
    networks:
      - sonarnet
  
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    restart: unless-stopped
    volumes:
      - ./sonarqube_db:/var/lib/postgresql
      - ./sonarqube_db_data:/var/lib/postgresql/data
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge