global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'archetype'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.137.237:8080' ]