services:
  redis_1:
    image: "redis:6.2"
    container_name: redis_1
    ports:
      - 7001:7001
      - 17001:17001
    volumes:
      - ./redis/cluster_1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.2

  redis_2:
    image: "redis:6.2"
    container_name: redis_2
    ports:
      - 7002:7002
      - 17002:17002
    volumes:
      - ./redis/cluster_2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.3

  redis_3:
    image: "redis:6.2"
    container_name: redis_3
    ports:
      - 7003:7003
      - 17003:17003
    volumes:
      - ./redis/cluster_3/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.4

  redis_4:
    image: "redis:6.2"
    container_name: redis_4
    ports:
      - 7004:7004
      - 17004:17004
    volumes:
      - ./redis/cluster_4/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.5

  redis_5:
    image: "redis:6.2"
    container_name: redis_5
    ports:
      - 7005:7005
      - 17005:17005
    volumes:
      - ./redis/cluster_5/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.6

  redis_6:
    image: "redis:6.2"
    container_name: redis_6
    ports:
      - 7006:7006
      - 17006:17006
    volumes:
      - ./redis/cluster_6/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.7

  cluster_initiator:
    container_name: cluster_initiator
    build:
      context: redis
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.8

networks:
  redis_cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16
