apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Tempo
  - name: Loki

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      timeout: 60
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3100
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      timeout: 60
      serviceMap:
        datasourceUid: 'prometheus'
      tracesToLogs:
        datasourceUid: 'loki'
        mapTagNamesEnabled: true
        mappedTags:
          - key: 'correlationID'
            value: 'correlationID'
          - key: 'service'
            value: 'service'
          - key: 'RequestID'
            value: 'RequestID'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
      nodeGraph:
        enabled: true
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    editable: true
    url: http://gateway:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      timeout: 60
      maxLines: 1000
    secureJsonData:
      httpHeaderValue1: "tenant1"