services:
  jenkins:
    image: "jenkins/jenkins:lts"
    build: .
    container_name: jenkins-container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data/jenkins:/var/jenkins_home
    restart: unless-stopped